name: Greetings on PR/Issue

on: [pull_request, issues]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          # Welcome ${{github.actor}} â¤ï¸! ğŸ‰ğŸ•
          Congrats to your _first issue_!
          **It is essential that you read the [developer guide](https://github.com/stefanini-applications/developer-guide).**
        
        pr-message: |
          # Welcome ${{github.actor}} â¤ï¸! ğŸ‰ğŸ•
          Congrats to your _first PR_!
          **It is essential that you read the [developer guide](https://github.com/stefanini-applications/developer-guide).**
